/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundRequestRouteImport } from './routes/refund-request'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderCancellationRouteImport } from './routes/order-cancellation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DeliveryInfoRouteImport } from './routes/delivery-info'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogHowToBuyNetflixInBangladeshRouteImport } from './routes/blog.how-to-buy-netflix-in-bangladesh'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrackingRouteImport } from './routes/admin.tracking'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReviewGeneratorRouteImport } from './routes/admin.review-generator'
import { Route as AdminRenewalRemindersRouteImport } from './routes/admin.renewal-reminders'
import { Route as AdminQuickToolsRouteImport } from './routes/admin.quick-tools'
import { Route as AdminQuickSaleRouteImport } from './routes/admin.quick-sale'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentLinksRouteImport } from './routes/admin.payment-links'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOrderRecoveryRouteImport } from './routes/admin.order-recovery'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminLiveChatRouteImport } from './routes/admin.live-chat'
import { Route as AdminLicenseManagerRouteImport } from './routes/admin.license-manager'
import { Route as AdminInvoiceGeneratorRouteImport } from './routes/admin.invoice-generator'
import { Route as AdminInvoiceDesignRouteImport } from './routes/admin.invoice-design'
import { Route as AdminEmailDashboardRouteImport } from './routes/admin.email-dashboard'
import { Route as AdminDescriptionTemplateRouteImport } from './routes/admin.description-template'
import { Route as AdminDescriptionPreviewRouteImport } from './routes/admin.description-preview'
import { Route as AdminCustomerLicensesRouteImport } from './routes/admin.customer-licenses'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminBulkUpdateRouteImport } from './routes/admin.bulk-update'
import { Route as AdminBkashTransactionsRouteImport } from './routes/admin.bkash-transactions'
import { Route as AdminAffiliatesRouteImport } from './routes/admin.affiliates'
import { Route as AdminAbandonedCheckoutRouteImport } from './routes/admin.abandoned-checkout'
import { Route as AdminPageRouteImport } from './routes/admin.$page'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'
import { Route as ApiPublicClientErrorsRouteImport } from './routes/api/public/client-errors'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRequestRoute = RefundRequestRouteImport.update({
  id: '/refund-request',
  path: '/refund-request',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCancellationRoute = OrderCancellationRouteImport.update({
  id: '/order-cancellation',
  path: '/order-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryInfoRoute = DeliveryInfoRouteImport.update({
  id: '/delivery-info',
  path: '/delivery-info',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToBuyNetflixInBangladeshRoute =
  BlogHowToBuyNetflixInBangladeshRouteImport.update({
    id: '/blog/how-to-buy-netflix-in-bangladesh',
    path: '/blog/how-to-buy-netflix-in-bangladesh',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewGeneratorRoute = AdminReviewGeneratorRouteImport.update({
  id: '/review-generator',
  path: '/review-generator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRenewalRemindersRoute = AdminRenewalRemindersRouteImport.update({
  id: '/renewal-reminders',
  path: '/renewal-reminders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickToolsRoute = AdminQuickToolsRouteImport.update({
  id: '/quick-tools',
  path: '/quick-tools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickSaleRoute = AdminQuickSaleRouteImport.update({
  id: '/quick-sale',
  path: '/quick-sale',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentLinksRoute = AdminPaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderRecoveryRoute = AdminOrderRecoveryRouteImport.update({
  id: '/order-recovery',
  path: '/order-recovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveChatRoute = AdminLiveChatRouteImport.update({
  id: '/live-chat',
  path: '/live-chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLicenseManagerRoute = AdminLicenseManagerRouteImport.update({
  id: '/license-manager',
  path: '/license-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceGeneratorRoute = AdminInvoiceGeneratorRouteImport.update({
  id: '/invoice-generator',
  path: '/invoice-generator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceDesignRoute = AdminInvoiceDesignRouteImport.update({
  id: '/invoice-design',
  path: '/invoice-design',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailDashboardRoute = AdminEmailDashboardRouteImport.update({
  id: '/email-dashboard',
  path: '/email-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDescriptionTemplateRoute =
  AdminDescriptionTemplateRouteImport.update({
    id: '/description-template',
    path: '/description-template',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDescriptionPreviewRoute = AdminDescriptionPreviewRouteImport.update({
  id: '/description-preview',
  path: '/description-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerLicensesRoute = AdminCustomerLicensesRouteImport.update({
  id: '/customer-licenses',
  path: '/customer-licenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBulkUpdateRoute = AdminBulkUpdateRouteImport.update({
  id: '/bulk-update',
  path: '/bulk-update',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBkashTransactionsRoute = AdminBkashTransactionsRouteImport.update({
  id: '/bkash-transactions',
  path: '/bkash-transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesRoute = AdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbandonedCheckoutRoute = AdminAbandonedCheckoutRouteImport.update({
  id: '/abandoned-checkout',
  path: '/abandoned-checkout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorsRoute = ApiPublicClientErrorsRouteImport.update({
  id: '/api/public/client-errors',
  path: '/api/public/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery-info': typeof DeliveryInfoRoute
  '/developer': typeof DeveloperRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-cancellation': typeof OrderCancellationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/refund-request': typeof RefundRequestRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wallet': typeof WalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/abandoned-checkout': typeof AdminAbandonedCheckoutRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/bkash-transactions': typeof AdminBkashTransactionsRoute
  '/admin/bulk-update': typeof AdminBulkUpdateRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-licenses': typeof AdminCustomerLicensesRoute
  '/admin/description-preview': typeof AdminDescriptionPreviewRoute
  '/admin/description-template': typeof AdminDescriptionTemplateRoute
  '/admin/email-dashboard': typeof AdminEmailDashboardRoute
  '/admin/invoice-design': typeof AdminInvoiceDesignRoute
  '/admin/invoice-generator': typeof AdminInvoiceGeneratorRoute
  '/admin/license-manager': typeof AdminLicenseManagerRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/order-recovery': typeof AdminOrderRecoveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-links': typeof AdminPaymentLinksRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-sale': typeof AdminQuickSaleRoute
  '/admin/quick-tools': typeof AdminQuickToolsRoute
  '/admin/renewal-reminders': typeof AdminRenewalRemindersRoute
  '/admin/review-generator': typeof AdminReviewGeneratorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/how-to-buy-netflix-in-bangladesh': typeof BlogHowToBuyNetflixInBangladeshRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery-info': typeof DeliveryInfoRoute
  '/developer': typeof DeveloperRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-cancellation': typeof OrderCancellationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/refund-request': typeof RefundRequestRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wallet': typeof WalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/abandoned-checkout': typeof AdminAbandonedCheckoutRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/bkash-transactions': typeof AdminBkashTransactionsRoute
  '/admin/bulk-update': typeof AdminBulkUpdateRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-licenses': typeof AdminCustomerLicensesRoute
  '/admin/description-preview': typeof AdminDescriptionPreviewRoute
  '/admin/description-template': typeof AdminDescriptionTemplateRoute
  '/admin/email-dashboard': typeof AdminEmailDashboardRoute
  '/admin/invoice-design': typeof AdminInvoiceDesignRoute
  '/admin/invoice-generator': typeof AdminInvoiceGeneratorRoute
  '/admin/license-manager': typeof AdminLicenseManagerRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/order-recovery': typeof AdminOrderRecoveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-links': typeof AdminPaymentLinksRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-sale': typeof AdminQuickSaleRoute
  '/admin/quick-tools': typeof AdminQuickToolsRoute
  '/admin/renewal-reminders': typeof AdminRenewalRemindersRoute
  '/admin/review-generator': typeof AdminReviewGeneratorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/how-to-buy-netflix-in-bangladesh': typeof BlogHowToBuyNetflixInBangladeshRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tools': typeof AiToolsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery-info': typeof DeliveryInfoRoute
  '/developer': typeof DeveloperRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/order-cancellation': typeof OrderCancellationRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/refund-request': typeof RefundRequestRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/streaming': typeof StreamingRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wallet': typeof WalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/abandoned-checkout': typeof AdminAbandonedCheckoutRoute
  '/admin/affiliates': typeof AdminAffiliatesRoute
  '/admin/bkash-transactions': typeof AdminBkashTransactionsRoute
  '/admin/bulk-update': typeof AdminBulkUpdateRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customer-licenses': typeof AdminCustomerLicensesRoute
  '/admin/description-preview': typeof AdminDescriptionPreviewRoute
  '/admin/description-template': typeof AdminDescriptionTemplateRoute
  '/admin/email-dashboard': typeof AdminEmailDashboardRoute
  '/admin/invoice-design': typeof AdminInvoiceDesignRoute
  '/admin/invoice-generator': typeof AdminInvoiceGeneratorRoute
  '/admin/license-manager': typeof AdminLicenseManagerRoute
  '/admin/live-chat': typeof AdminLiveChatRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/order-recovery': typeof AdminOrderRecoveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-links': typeof AdminPaymentLinksRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/quick-sale': typeof AdminQuickSaleRoute
  '/admin/quick-tools': typeof AdminQuickToolsRoute
  '/admin/renewal-reminders': typeof AdminRenewalRemindersRoute
  '/admin/review-generator': typeof AdminReviewGeneratorRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/blog/how-to-buy-netflix-in-bangladesh': typeof BlogHowToBuyNetflixInBangladeshRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-tools'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/delivery-info'
    | '/developer'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/order-cancellation'
    | '/orders'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/refund-policy'
    | '/refund-request'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/streaming'
    | '/terms'
    | '/unsubscribe'
    | '/wallet'
    | '/admin/$page'
    | '/admin/abandoned-checkout'
    | '/admin/affiliates'
    | '/admin/bkash-transactions'
    | '/admin/bulk-update'
    | '/admin/coupons'
    | '/admin/customer-licenses'
    | '/admin/description-preview'
    | '/admin/description-template'
    | '/admin/email-dashboard'
    | '/admin/invoice-design'
    | '/admin/invoice-generator'
    | '/admin/license-manager'
    | '/admin/live-chat'
    | '/admin/newsletter'
    | '/admin/order-recovery'
    | '/admin/orders'
    | '/admin/payment-links'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/quick-sale'
    | '/admin/quick-tools'
    | '/admin/renewal-reminders'
    | '/admin/review-generator'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/themes'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/how-to-buy-netflix-in-bangladesh'
    | '/email/unsubscribe'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin/'
    | '/api/public/client-errors'
    | '/api/public/products'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tools'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/delivery-info'
    | '/developer'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/order-cancellation'
    | '/orders'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/refund-policy'
    | '/refund-request'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/streaming'
    | '/terms'
    | '/unsubscribe'
    | '/wallet'
    | '/admin/$page'
    | '/admin/abandoned-checkout'
    | '/admin/affiliates'
    | '/admin/bkash-transactions'
    | '/admin/bulk-update'
    | '/admin/coupons'
    | '/admin/customer-licenses'
    | '/admin/description-preview'
    | '/admin/description-template'
    | '/admin/email-dashboard'
    | '/admin/invoice-design'
    | '/admin/invoice-generator'
    | '/admin/license-manager'
    | '/admin/live-chat'
    | '/admin/newsletter'
    | '/admin/order-recovery'
    | '/admin/orders'
    | '/admin/payment-links'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/quick-sale'
    | '/admin/quick-tools'
    | '/admin/renewal-reminders'
    | '/admin/review-generator'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/themes'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/how-to-buy-netflix-in-bangladesh'
    | '/email/unsubscribe'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin'
    | '/api/public/client-errors'
    | '/api/public/products'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-tools'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/delivery-info'
    | '/developer'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/order-cancellation'
    | '/orders'
    | '/privacy-policy'
    | '/products'
    | '/profile'
    | '/refund-policy'
    | '/refund-request'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/streaming'
    | '/terms'
    | '/unsubscribe'
    | '/wallet'
    | '/admin/$page'
    | '/admin/abandoned-checkout'
    | '/admin/affiliates'
    | '/admin/bkash-transactions'
    | '/admin/bulk-update'
    | '/admin/coupons'
    | '/admin/customer-licenses'
    | '/admin/description-preview'
    | '/admin/description-template'
    | '/admin/email-dashboard'
    | '/admin/invoice-design'
    | '/admin/invoice-generator'
    | '/admin/license-manager'
    | '/admin/live-chat'
    | '/admin/newsletter'
    | '/admin/order-recovery'
    | '/admin/orders'
    | '/admin/payment-links'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/quick-sale'
    | '/admin/quick-tools'
    | '/admin/renewal-reminders'
    | '/admin/review-generator'
    | '/admin/reviews'
    | '/admin/security'
    | '/admin/themes'
    | '/admin/tickets'
    | '/admin/tracking'
    | '/admin/users'
    | '/admin/wallet'
    | '/blog/how-to-buy-netflix-in-bangladesh'
    | '/email/unsubscribe'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin/'
    | '/api/public/client-errors'
    | '/api/public/products'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiToolsRoute: typeof AiToolsRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryInfoRoute: typeof DeliveryInfoRoute
  DeveloperRoute: typeof DeveloperRoute
  EducationRoute: typeof EducationRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OrderCancellationRoute: typeof OrderCancellationRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RefundRequestRoute: typeof RefundRequestRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StreamingRoute: typeof StreamingRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WalletRoute: typeof WalletRoute
  BlogHowToBuyNetflixInBangladeshRoute: typeof BlogHowToBuyNetflixInBangladeshRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicClientErrorsRoute: typeof ApiPublicClientErrorsRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-request': {
      id: '/refund-request'
      path: '/refund-request'
      fullPath: '/refund-request'
      preLoaderRoute: typeof RefundRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-cancellation': {
      id: '/order-cancellation'
      path: '/order-cancellation'
      fullPath: '/order-cancellation'
      preLoaderRoute: typeof OrderCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-info': {
      id: '/delivery-info'
      path: '/delivery-info'
      fullPath: '/delivery-info'
      preLoaderRoute: typeof DeliveryInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-buy-netflix-in-bangladesh': {
      id: '/blog/how-to-buy-netflix-in-bangladesh'
      path: '/blog/how-to-buy-netflix-in-bangladesh'
      fullPath: '/blog/how-to-buy-netflix-in-bangladesh'
      preLoaderRoute: typeof BlogHowToBuyNetflixInBangladeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review-generator': {
      id: '/admin/review-generator'
      path: '/review-generator'
      fullPath: '/admin/review-generator'
      preLoaderRoute: typeof AdminReviewGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/renewal-reminders': {
      id: '/admin/renewal-reminders'
      path: '/renewal-reminders'
      fullPath: '/admin/renewal-reminders'
      preLoaderRoute: typeof AdminRenewalRemindersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-tools': {
      id: '/admin/quick-tools'
      path: '/quick-tools'
      fullPath: '/admin/quick-tools'
      preLoaderRoute: typeof AdminQuickToolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-sale': {
      id: '/admin/quick-sale'
      path: '/quick-sale'
      fullPath: '/admin/quick-sale'
      preLoaderRoute: typeof AdminQuickSaleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-links': {
      id: '/admin/payment-links'
      path: '/payment-links'
      fullPath: '/admin/payment-links'
      preLoaderRoute: typeof AdminPaymentLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order-recovery': {
      id: '/admin/order-recovery'
      path: '/order-recovery'
      fullPath: '/admin/order-recovery'
      preLoaderRoute: typeof AdminOrderRecoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-chat': {
      id: '/admin/live-chat'
      path: '/live-chat'
      fullPath: '/admin/live-chat'
      preLoaderRoute: typeof AdminLiveChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/license-manager': {
      id: '/admin/license-manager'
      path: '/license-manager'
      fullPath: '/admin/license-manager'
      preLoaderRoute: typeof AdminLicenseManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice-generator': {
      id: '/admin/invoice-generator'
      path: '/invoice-generator'
      fullPath: '/admin/invoice-generator'
      preLoaderRoute: typeof AdminInvoiceGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice-design': {
      id: '/admin/invoice-design'
      path: '/invoice-design'
      fullPath: '/admin/invoice-design'
      preLoaderRoute: typeof AdminInvoiceDesignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email-dashboard': {
      id: '/admin/email-dashboard'
      path: '/email-dashboard'
      fullPath: '/admin/email-dashboard'
      preLoaderRoute: typeof AdminEmailDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/description-template': {
      id: '/admin/description-template'
      path: '/description-template'
      fullPath: '/admin/description-template'
      preLoaderRoute: typeof AdminDescriptionTemplateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/description-preview': {
      id: '/admin/description-preview'
      path: '/description-preview'
      fullPath: '/admin/description-preview'
      preLoaderRoute: typeof AdminDescriptionPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-licenses': {
      id: '/admin/customer-licenses'
      path: '/customer-licenses'
      fullPath: '/admin/customer-licenses'
      preLoaderRoute: typeof AdminCustomerLicensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bulk-update': {
      id: '/admin/bulk-update'
      path: '/bulk-update'
      fullPath: '/admin/bulk-update'
      preLoaderRoute: typeof AdminBulkUpdateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bkash-transactions': {
      id: '/admin/bkash-transactions'
      path: '/bkash-transactions'
      fullPath: '/admin/bkash-transactions'
      preLoaderRoute: typeof AdminBkashTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates': {
      id: '/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AdminAffiliatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abandoned-checkout': {
      id: '/admin/abandoned-checkout'
      path: '/abandoned-checkout'
      fullPath: '/admin/abandoned-checkout'
      preLoaderRoute: typeof AdminAbandonedCheckoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-errors': {
      id: '/api/public/client-errors'
      path: '/api/public/client-errors'
      fullPath: '/api/public/client-errors'
      preLoaderRoute: typeof ApiPublicClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminAbandonedCheckoutRoute: typeof AdminAbandonedCheckoutRoute
  AdminAffiliatesRoute: typeof AdminAffiliatesRoute
  AdminBkashTransactionsRoute: typeof AdminBkashTransactionsRoute
  AdminBulkUpdateRoute: typeof AdminBulkUpdateRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomerLicensesRoute: typeof AdminCustomerLicensesRoute
  AdminDescriptionPreviewRoute: typeof AdminDescriptionPreviewRoute
  AdminDescriptionTemplateRoute: typeof AdminDescriptionTemplateRoute
  AdminEmailDashboardRoute: typeof AdminEmailDashboardRoute
  AdminInvoiceDesignRoute: typeof AdminInvoiceDesignRoute
  AdminInvoiceGeneratorRoute: typeof AdminInvoiceGeneratorRoute
  AdminLicenseManagerRoute: typeof AdminLicenseManagerRoute
  AdminLiveChatRoute: typeof AdminLiveChatRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrderRecoveryRoute: typeof AdminOrderRecoveryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentLinksRoute: typeof AdminPaymentLinksRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminQuickSaleRoute: typeof AdminQuickSaleRoute
  AdminQuickToolsRoute: typeof AdminQuickToolsRoute
  AdminRenewalRemindersRoute: typeof AdminRenewalRemindersRoute
  AdminReviewGeneratorRoute: typeof AdminReviewGeneratorRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminAbandonedCheckoutRoute: AdminAbandonedCheckoutRoute,
  AdminAffiliatesRoute: AdminAffiliatesRoute,
  AdminBkashTransactionsRoute: AdminBkashTransactionsRoute,
  AdminBulkUpdateRoute: AdminBulkUpdateRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomerLicensesRoute: AdminCustomerLicensesRoute,
  AdminDescriptionPreviewRoute: AdminDescriptionPreviewRoute,
  AdminDescriptionTemplateRoute: AdminDescriptionTemplateRoute,
  AdminEmailDashboardRoute: AdminEmailDashboardRoute,
  AdminInvoiceDesignRoute: AdminInvoiceDesignRoute,
  AdminInvoiceGeneratorRoute: AdminInvoiceGeneratorRoute,
  AdminLicenseManagerRoute: AdminLicenseManagerRoute,
  AdminLiveChatRoute: AdminLiveChatRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrderRecoveryRoute: AdminOrderRecoveryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentLinksRoute: AdminPaymentLinksRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminQuickSaleRoute: AdminQuickSaleRoute,
  AdminQuickToolsRoute: AdminQuickToolsRoute,
  AdminRenewalRemindersRoute: AdminRenewalRemindersRoute,
  AdminReviewGeneratorRoute: AdminReviewGeneratorRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiToolsRoute: AiToolsRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DeliveryInfoRoute: DeliveryInfoRoute,
  DeveloperRoute: DeveloperRoute,
  EducationRoute: EducationRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrderCancellationRoute: OrderCancellationRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RefundRequestRoute: RefundRequestRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StreamingRoute: StreamingRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WalletRoute: WalletRoute,
  BlogHowToBuyNetflixInBangladeshRoute: BlogHowToBuyNetflixInBangladeshRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicClientErrorsRoute: ApiPublicClientErrorsRoute,
  ApiPublicProductsRoute: ApiPublicProductsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
