
INSERT INTO public.admin_records (kind, data, is_active, sort_order) VALUES
('help_article', jsonb_build_object('title','Order দেওয়ার পর কতক্ষণে account পাব?','slug','order-delivery-time','category','orders','body','সাধারণত 10–30 মিনিটের মধ্যে account delivery হয়। অফিস আওয়ারে (11 AM – 11 PM) আরও দ্রুত। অফিস বন্ধ থাকলে সর্বোচ্চ 3 ঘণ্টার মধ্যে delivery নিশ্চিত করা হয়। Order status ট্র্যাক করতে "My Orders" পেজে যান।'), true, 0),
('help_article', jsonb_build_object('title','bKash / Nagad-এ payment কীভাবে করব?','slug','bkash-nagad-payment-guide','category','payment','body','Checkout পেজে bKash/Nagad select করুন → আমাদের merchant number-এ send money করুন → transaction ID টি form-এ paste করে submit করুন। কয়েক মিনিটের মধ্যে confirmation email পাবেন।'), true, 1),
('help_article', jsonb_build_object('title','Warranty কতদিনের এবং কী কী cover করে?','slug','warranty-policy','category','warranty','body','সব premium account-এ 30 দিনের full warranty দেওয়া হয়। এই সময়ের মধ্যে account কাজ না করলে replacement অথবা full refund পাবেন — কোনো প্রশ্ন ছাড়াই।'), true, 2),
('help_article', jsonb_build_object('title','Account login না হলে কী করব?','slug','account-login-not-working','category','technical','body','প্রথমে email/password সঠিকভাবে copy-paste করে দেখুন। তারপরও কাজ না করলে সাথে সাথে WhatsApp-এ মেসেজ দিন — 5-10 মিনিটের মধ্যে fresh login credential পাঠানো হবে।'), true, 3),
('help_article', jsonb_build_object('title','একই account কতজন ব্যবহার করতে পারব?','slug','account-sharing-limit','category','subscription','body','Product এর ধরন অনুযায়ী শেয়ার-সীমা আলাদা। Netflix/Prime এ সাধারণত 1-4 screen, Shared accounts এ 1 device recommended। প্রতিটি product page-এ বিস্তারিত limit উল্লেখ থাকে।'), true, 4),
('help_article', jsonb_build_object('title','Refund কীভাবে পাব এবং কতদিন লাগে?','slug','refund-process','category','warranty','body','Refund request WhatsApp/Support ticket-এ জানান। Approval-এর পর bKash/Nagad-এ 24–48 ঘণ্টার মধ্যে টাকা ফেরত পাবেন। Card payment এর ক্ষেত্রে 5-7 working day লাগতে পারে।'), true, 5),
('help_article', jsonb_build_object('title','Order cancel করতে চাই','slug','cancel-order','category','orders','body','Delivery-র আগ পর্যন্ত order cancel করা যাবে। WhatsApp-এ order ID সহ মেসেজ দিন। Delivery হয়ে গেলে warranty policy অনুযায়ী refund process follow করতে হবে।'), true, 6),
('help_article', jsonb_build_object('title','Invoice/receipt কোথায় পাব?','slug','invoice-receipt','category','account','body','Order confirm হওয়ার সাথে সাথে registered email-এ automatic invoice পাঠানো হয়। এছাড়া Dashboard → My Orders → নির্দিষ্ট order-এ ক্লিক করে যেকোনো সময় invoice download করা যাবে।'), true, 7);
